resolver: lts-8.2

packages:
- '.'
# - '../isobmff-builder' ## uncomment for local development

extra-deps:
- pretty-types-0.2.3.1
- type-spec-0.3.0.1
- isobmff-builder-0.11.3.0   ## comment for local development

flags: {}

extra-package-dbs: []
